CREATE TABLE IF NOT EXISTS readwise(
    id TEXT PRIMARY KEY NOT NULL,
    url TEXT NOT NULL,
    title TEXT,
    created_at DATETIME DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS api_keys(
    id TEXT PRIMARY KEY NOT NULL,
    key_name TEXT NOT NULL,
    key_value TEXT NOT NULL,
    created_at DATETIME DEFAULT (CURRENT_TIMESTAMP)
);
